#!/bin/bash
set -e
$POSTGRES <<EOSQL
su -p ${POSTGRES_USERNAME} psql
CREATE DATABASE ${POSTGRES_DB}
CREATE USER ${POSTGRES_USERNAME} WITH password ${POSTGRES_PASSWORD}
GRANT ALL ON DATABASE ${POSTGRES_USERNAME} TO ${POSTGRES_USERNAME}
EOSQL
