version: "3"

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: always
        volumes:
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
            - './:/app'
            - './.logs/nginx:/var/log/nginx'
        ports:
            - "8080:80"
        depends_on:
            - postgres
            - php

    php:
        container_name: php
        build: ./docker/php
        volumes:
            - "./:/app"
        depends_on:
            - postgres
        environment:
            - PHP_VERSION=8.1.14-fpm

    postgres:
        container_name: postgres
        build: ./docker/postgres
        restart: always
        env_file: ./.env
        environment:
            - POSTGRES_USERNAME=${DB_USERNAME}
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_PORT=${DB_PORT}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - './app:/app'
            - './.database:/var/lib/pgsql/data'
        ports:
            - '1010:5432'
